== Javascript 

Most of the componants discussed in the previous chapter are just the beginning. Bootstrap comes bundled with 13 jQuery plugins that that extend the features, and can add more interaction to your sute.

=== Overview

Bootstrap cand be included on your site in two forms, either compiled or raw. Bootstrap 2.2.2 the uncompressed file is 59kb, and the minimized version is only 32kb. All of the Bootstrap plugins are accessible entirely using the included data API, with this, you don't need to include a single line of javascript to invoke any of the plugins features.

If you need to turn off the data API, you can unbind the attributes by adding this line of Javascript.

.Disable Bootstrap Javascript Data API
[source, js]
----
$('body').off('.data-api')
----

If you need to disable a single plugin, you can do it programmatically using the namespace of the plugin along with the `data-api` namespace.

.Disable an Individual Plugin
[source, js]
----
$('body').off('.alert.data-api')
----

==== Programattic API

The devlelopers of Bootstrap believe that you should be able to use all of the plugins entirely throught the Javascript API. All public APIs are single, chainable methods, and return the collection acted upon.

[source, js]
----
$('.btn.danger').button('toggle').addClass('active')
----

All methods should accept an optional options object, a string which targets a particular method, or nothing (which initiates a plugin with default behavior).

[source, js]
----
$("#myModal").modal()						// initialized with defaults
$("#myModal").modal({ keyboard: false })	// initialized with no keyboard
$("#myModal").modal('show')					// initializes and invokes show immediately
----

=== Transitions

=== Modal

=== Dropdown

=== Scrollspy

=== Tab

=== Tooltip

=== Popover

=== Alert

=== Button

=== Collapse

=== Carousel

=== Typeahead

=== Affix
