== Using Bootstrap

=== Github Project

Like a lot of great open source projects, the power of Bootstrap comes not just from the developers at the core of the project, but also from the developement community that supports it. (GitHub)[http://github.com] is a large code repository for projects, and at time of writing, Bootstrap is the most popular project. With over 42,000 stars, and over 10,000 forks, the project is bustling with activity. Like I mentioned in chapter 1, if you want to use Bootstrap, you can simply download the .zip archive from the site, or you can download using `git`.

For the unitiated, `git` is a free and open source version control system. Bootstrap, and a host of other projects manage everything using Github, which is an online code repository for `git` projects. To download the source for Bootstrap, run the following commands from the command line.

[source, bash]
----
$ git clone https://github.com/twitter/bootstrap.git
----

Cloning the Rootstrap will give you a full download of all the files, not just the CSS/Javascript but also all of the documentation pages, and the LESS files for the dynamic Javascript elements.

=== Built with Bootstrap

=== Variables

=== Mixins

=== Compiling Bootstrap