[colophon]
= Colophon

The animal on the cover of _Bootstrap_ is the Finnhorse. The Finnhorse is the official horse of Finland, and is nicknamed as the "universal horse" for its ability to meet the agricultural, economic, or recreational needs that a person might require from a horse.  Though it has been fully bred and cultivated in Finland for centuries, the exact origin of this horse is unknown.  

The vast majority of Finnhorses are a chestnut color, with a very small percentage being black, silver, or bay-colored. In the 1800s, the chestnut-colored Finnhorse only accounted for roughly half the population, but through selective breeding throughout the 19th and 20th centuries, most other genes were bred out, as it was determined that chestnut was the original color of the breed and the national Finnish horse breeding association sought to eliminate "foreign" colors. It was also selectively bred to be an average-sized-horse--the average height is 61 inches--with the ability and muscles to do hard-labor and the agility to be used for the purposes of riding or entertainment.  

Today, most Finnhorses are used for harness racing and for other recreational purposes.  It was originally the only horse used for racing in Finland, but after the middle of the 20th century other horses were introduced into the sport. The horse is also used frequently at riding schools and for therapy.   

The cover image is from a loose plate of german origin, exact source unknown. The cover font is Adobe ITC Garamond. The text font is Adobe Minion Pro; the heading font is Adobe Myriad Condensed; and the code font is Dalton Maag's Ubuntu Mono.
